[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://swapspace-backend.herokuapp.com/api/v1"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://swapspace-staging-backend.herokuapp.com/api/v1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"